
# Translates all text files on the text directory without needing to select 1 by 1. (Slower But more convenient)
translate_all: true

# Directories
text_dir: "./text"
save_dir: "./saves"

# File Types
pickled_save: false # Will use json if set to false

# Translator will only display files with this file type
# dont include the (.)
text_type: "txt" 