#!/usr/bin/env python3

import sys
import time
from json import dump

# HELP
try:
    if sys.argv[1].lower() in ['help', '--help', '-h']:
        print(f'use: py {sys.argv[0]} path outputpath')
        exit()
except IndexError:
    pass


try:
    file = open(f'{sys.argv[1]}.txt')
except:
    print(
        f'ERROR: No path was given \nuse: `py {sys.argv[0]} path outputpath(optional)`')
    exit()

try:
    outputpath = sys.argv[2]
except IndexError:
    outputpath = './notes/'+sys.argv[1]+'.json'

starttime = time.time()


def cleanup(content: list[str]):
    finished: list[str] = []
    content2: list[str] = []
    for line in content:
        if not line.startswith('\n'):
            if not line.startswith('#'):
                content2.append(line)
                
    for line in content2:
        line = line.replace(' = ', '=')
        line = line.replace(' =', '=')
        line = line.replace('= ', '=')
        line = line.replace('-- ', '--')
        line = line.replace('- ', '-')
        line = line.replace('\n', '')
        line = line.strip()
        finished.append(line)
    return finished


enummode = False
key: str = ''
value = ''
data = {}

for line in cleanup(file.readlines()):
    if not line.startswith('-'):
        if enummode == True:
            data[key] = value
            enummode = False
        line = line.split('=')
        key, value = line
        data[value] = key

    else:
        if line.startswith('--'):
            if enummode == True:
                data[key] = value
            enummode = True
            key = line.removeprefix('--')
            value = []
        else:
            value.append(line.removeprefix('-'))

if type(value) == list:
    data[key] = value


dump(data, open(outputpath, 'w'), indent=2)

print('file outputted at:', outputpath)
print('total generation time:', str(round(time.time()-starttime, 3))+'s')
